### ISSUE TITLE
Can't update existing lambda function because of lambda update status 'in progess'

### ISSUE THREAD

**Issue by kimsehwan96** [aws-iot-builder-tools/aws-greengrass-provisioner#968]
Hi, @timmattison 

Updating existing lambda with  greengrass provisioner isn't working because of '`lambda state` especially `LastUpdateStatus`. 

refer to  https://aws.amazon.com/ko/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/

<img width="986" alt="스크린샷 2021-11-25 오후 11 08 37" src="https://user-images.githubusercontent.com/59886140/143456012-afa07498-e984-4a94-a34d-ff9a23a39cea.png">

When greengrass provisioner update existing lambda by uploading zip file to S3, lambda that updated is in LastUpdateStatus 'in progress' like following image.

<img width="858" alt="스크린샷 2021-11-25 오후 11 10 51" src="https://user-images.githubusercontent.com/59886140/143456382-d78aeda6-9adb-4dec-8fb3-918c168e5fbe.png">

After few seconds, lambda that updated is in LastUpdateStatus `Successful` status and successfully updated. (creating function)

But 'greengrass provisioner' doesn't wait for this status changing (In progress -> Successful) so updating is failed.  (updating lambda configuration, version, alias etc..)

We need to wait state changing delay for `LastUpateStatus`  in https://github.com/awslabs/aws-greengrass-provisioner/blob/4c971f1df490c7f57f0699962368bb52e089d7db/src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicLambdaHelper.java#L230

**Comment by timmattison** [comment]
I think this looks reasonable. Let me check in tomorrow and do some testing and then I'll merge it if it looks good.

**Comment by timmattison** [comment]
Thank you for filing this issue AND creating a PR! Sorry it was overlooked for a while.
